SocialNetwork.Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialNetwork.Web.Models;
using System.Diagnostics;

namespace SocialNetwork.Web.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<DashboardController> _logger;

        public DashboardController(ILogger<DashboardController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SocialNetwork.Web/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace SocialNetwork.Web.Controllers
{
    public class LayoutController : Controller
    {
        public IActionResult StarterPage()
        {
            return View();
        }

        public IActionResult FixedFooter()
        {
            return View();
        }

        public IActionResult FullHeight()
        {
            return View();
        }

        public IActionResult FullWidth()
        {
            return View();
        }

        public IActionResult BoxedLayout()
        {
            return View();
        }

        public IActionResult MinifiedSidebar()
        {
            return View();
        }
    }
}

SocialNetwork.Web/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SocialNetwork.Domain.Entities;
using SocialNetwork.Domain.Interfaces.Repositories;
using System;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace SocialNetwork.Web.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IProfileRepository _profileRepository;

        public ProfileController(UserManager<User> userManager,
                                 IProfileRepository profileRepository)
        {
            _userManager = userManager;
            _profileRepository = profileRepository;
         }

        //action para exibição da view
        public async Task<IActionResult> Edit()
        {
            //recuperando user completo do banco de dados
            var currentUserId = _userManager.GetUserId(User);

            //obter a entidade perfil
            var profile = await _profileRepository.GetProfileByUserIdAsync(currentUserId);

            return View(profile);
        }

        //action para atualização dos dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] Profile profileForm)
        {
            //recuperando user completo do banco de dados
            var currentUserId = _userManager.GetUserId(User);

            //obter a entidade perfil
            var profileFromBd = await _profileRepository.GetProfileByUserIdAsync(currentUserId);
            
            //atribuindo o id do user (identity) ao profile
            profileForm.UserId = currentUserId;

            //validando se usuário existe em banco, e se existir, valida id do formulário com id do banco
            if (profileFromBd == null)
            {
                await _profileRepository.InsertAsync(profileForm);
                return RedirectToAction(nameof(Edit));
            }
            else
            {
                if (profileFromBd.Id != profileForm.Id)
                    throw new ApplicationException("UserId is different from database");

                //mantendo integro a imagem de profile (se existir)
                profileForm.UriImageProfile = profileFromBd.UriImageProfile;

                //atualizando no banco de dados
                await _profileRepository.UpdateAsync(profileForm);
            }

            ViewBag.ShowMessage = true;
            return View(profileForm);
        }

        [HttpPost]
        public async Task<IActionResult> EditImageProfile(IFormCollection form,
                                                          [FromServices] IHttpClientFactory clientFactory)
        {
            using (var content = new MultipartFormDataContent())
            {
                foreach (var file in form.Files)
                {
                    content.Add(CreateFileContent(file.OpenReadStream(), file.FileName, file.ContentType));
                }

                var httpClient = clientFactory.CreateClient();
                var response = await httpClient.PostAsync("api/image", content);

                response.EnsureSuccessStatusCode();
                var responseResult = await response.Content.ReadAsStringAsync();
                var uriImage = JsonConvert.DeserializeObject<string[]>(responseResult).FirstOrDefault();

                //recuperando user completo do banco de dados
                var currentUserId = _userManager.GetUserId(User);

                //obter a entidade perfil do banco
                var profileFromBd = await _profileRepository.GetProfileByUserIdAsync(currentUserId);
                if (profileFromBd == null)
                {
                    var profileToInsert = new Profile();
                    profileToInsert.UserId = currentUserId;
                    profileToInsert.UriImageProfile = uriImage;
                    await _profileRepository.InsertAsync(profileToInsert);
                }
                else
                {
                    profileFromBd.UriImageProfile = uriImage;
                    await _profileRepository.UpdateAsync(profileFromBd);
                }
            }

            return RedirectToAction(nameof(Edit));
        }

        private StreamContent CreateFileContent(Stream stream, string fileName, string contentType)
        {
            var fileContent = new StreamContent(stream);
            fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
            {
                Name = "\"files\"",
                FileName = "\"" + fileName + "\""
            };

            fileContent.Headers.ContentType = new MediaTypeHeaderValue(contentType);
            return fileContent;
        }
    }
}

SocialNetwork.Web/Views/Shared/_Footer.cshtml
<!-- BEGIN #footer -->
<div id="footer" class="app-footer">
    &copy; 2021 Rede do JC - Todos os direitos reservados
</div>
<!-- END #footer -->

SocialNetwork.Web/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Identity
@using SocialNetwork.Domain.Entities
@using SocialNetwork.Domain.Interfaces.Repositories

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject IProfileRepository profileRepo

@{
    var userIdentity = await UserManager.GetUserAsync(User);
    var profile = await profileRepo.GetProfileByUserIdAsync(userIdentity?.Id);

}

<!-- BEGIN #header -->
<div id="header" class="app-header">
    <!-- BEGIN mobile-toggler -->
    <div class="mobile-toggler">
        <button type="button" class="menu-toggler" data-toggle="sidebar-mobile">
            <span class="bar"></span>
            <span class="bar"></span>
        </button>
    </div>
    <!-- END mobile-toggler -->
    <!-- BEGIN brand -->
    <div class="brand">
        <div class="desktop-toggler">
            <button type="button" class="menu-toggler" data-toggle="sidebar-minify">
                <span class="bar"></span>
                <span class="bar"></span>
            </button>
        </div>

        <a href="/" class="brand-logo">
            <img src="~/img/brand/camell_text_logo.svg" alt="" height="20" />
        </a>
    </div>
    <!-- END brand -->
    <!-- BEGIN menu -->
    <div class="menu">
        <form class="menu-search" method="POST" name="header_search_form">
            <div class="menu-search-icon"><i class="fa fa-search"></i></div>
            <div class="menu-search-input">
                <input type="text" class="form-control" placeholder="Pesquisa ..." />
            </div>
        </form>
        <div class="menu-item dropdown">
            <a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
                <div class="menu-img online">
                    <img src="@(profile?.UriImageProfile != null ? profile.UriImageProfile : "/img/user/user.jpg")" alt="" class="mw-100 mh-100 rounded-circle" />
                </div>
                <div class="menu-text">@User.Identity.Name</div>
            </a>
            <div class="dropdown-menu dropdown-menu-end me-lg-3">
                <a class="dropdown-item d-flex align-items-center" href="@Url.ActionLink("Edit", "Profile", new { area = "" })">Editar Perfil <i class="fa fa-user-circle fa-fw ms-auto text-gray-400 f-s-16"></i></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item d-flex align-items-center" href="/Identity/Account/Logout?returnUrl=@Url.Action("Index", "Dashboard", new { area = "" })">Sair <i class="fa fa-toggle-off fa-fw ms-auto text-gray-400 f-s-16"></i></a>
            </div>
        </div>
    </div>
    <!-- END menu -->
</div>
<!-- END #header -->

SocialNetwork.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" @ViewData["HtmlAttribute"]>
<head>
    <meta charset="utf-8" />
    <title>CAMELLonCASE | @ViewData["Title"]</title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="@ViewData["MetaDescription"]" />
    <meta name="author" content="@ViewData["MetaAuthor"]" />
    <meta name="keywords" content="@ViewData["MetaKeywords"]" />

    @RenderSection("MetaTag", required: false)

    <!-- ================== BEGIN core-css ================== -->
    <link href="~/css/app.min.css" rel="stylesheet" />
    <!-- ================== END core-css ================== -->

    @RenderSection("Styles", required: false)
</head>
<body class="@ViewData["BodyClass"]">
    <!-- BEGIN #app -->
    <div id="app" class="app @ViewData["AppClass"]">
        @if (ViewData["AppWithoutHeader"] == null)
        {
            <partial name="_Header" />
        }

        @if (ViewData["AppWithoutSidebar"] == null)
        {
            <partial name="_Sidebar" />
        }

        @if (ViewData["AppWithoutContainer"] == null)
        {
            <div id="content" class="app-content @ViewData["AppContentClass"]">
                @RenderBody()

                <!-- BEGIN btn-scroll-top -->
                <a href="#" data-click="scroll-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>
                <!-- END btn-scroll-top -->
            </div>
        } else {
            @RenderBody()

            <!-- BEGIN btn-scroll-top -->
            <a href="#" data-click="scroll-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>
            <!-- END btn-scroll-top -->
        }

        @RenderSection("OutterAppContainerContent", required: false)

        @if (ViewData["AppWithFooter"] != null)
        {
            <partial name="_Footer" />
        }
    </div>

    <!-- ================== BEGIN core-js ================== -->
    <script src="~/js/app.min.js"></script>
    <!-- ================== END core-js ================== -->
    @RenderSection("Scripts", required: false)
</body>
</html>

SocialNetwork.Web/Views/Shared/_Sidebar.cshtml
@using Microsoft.Extensions.Configuration
@using Microsoft.AspNetCore.Identity
@using SocialNetwork.Domain.Entities
@using SocialNetwork.Domain.Interfaces.Repositories

@inject IConfiguration Configuration
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@inject IProfileRepository profileRepo

@{
    var userIdentity = await UserManager.GetUserAsync(User);
    var profile = await profileRepo.GetProfileByUserIdAsync(userIdentity?.Id);

    var menuController = (ViewContext.RouteData.Values["controller"] != null) ? ViewContext.RouteData.Values["controller"].ToString() : null;
    var menuAction = (ViewContext.RouteData.Values["action"] != null) ? ViewContext.RouteData.Values["action"].ToString() : null;
    var sidebarMenu = Configuration.GetSection("sidebarMenu").GetChildren().ToArray();
}

<!-- BEGIN #sidebar -->
<div id="sidebar" class="app-sidebar">
    <!-- BEGIN scrollbar -->
    <div class="app-sidebar-content" data-scrollbar="true" data-height="100%">
        
        

        <!-- BEGIN menu -->
        <div class="menu">

            <div class="menu-header">
                <span class="menu-icon">
                    <i>
                        <img src="@(profile?.UriImageProfile != null ? profile.UriImageProfile : "/img/user/user.jpg")" alt="" class="mw-100 mh-100 rounded-circle" width="40"/>
                    </i>
                    <span class="menu-icon-label">@profile?.FullName</span>
                </span>
            </div>

            @foreach (var menu in sidebarMenu)
            {
                var menuChildren = menu.GetSection("children").GetChildren().ToArray();

                @if (menu["is_header"] != null)
                {
                    <div class="menu-header">
                        @menu["text"]
                    </div>
                }
                else if (menu["is_divider"] != null)
                {
                    <div class="menu-divider"></div>
                }
                else
                {
                    <div class="menu-item @(menuController == @menu["controller"] ? "active" : "") @(menuChildren.Length > 0 ? "has-sub" : "")">

                        @if (menu["action"] != null && menu["controller"] != null)
                        {
                            <a asp-controller="@menu["controller"]" asp-action="@menu["action"]" asp-area="@menu["area"]" class="menu-link">
                                <span class="menu-icon">
                                    @if (menu["icon"] != null)
                                    {
                                        <i class="@menu["icon"]"></i>
                                    }
                                    @if (menu["label"] != null)
                                    {
                                        <span class="menu-icon-label">@menu["label"]</span>
                                    }
                                </span>
                                <span class="menu-text">@menu["text"]</span>
                            </a>
                        }
                        else
                        {
                            <a href="#" class="menu-link">
                                <span class="menu-icon">
                                    @if (menu["icon"] != null)
                                    {
                                        <i class="@menu["icon"]"></i>
                                    }
                                    @if (menu["label"] != null)
                                    {
                                        <span class="menu-icon-label">@menu["label"]</span>
                                    }
                                </span>
                                <span class="menu-text">@menu["text"]</span>
                                @if (menuChildren.Length > 0)
                                {
                                    <span class="menu-caret"><b class="caret"></b></span>
                                }
                            </a>
                        }
                        @if (menuChildren.Length > 0)
                        {
                            <div class="menu-submenu">
                                @foreach (var submenu in menuChildren)
                                {
                                    <div class="menu-item @(menuAction == @submenu["action"] ? "active" : "")">
                                        <a asp-controller="@submenu["controller"]" asp-action="@submenu["action"]" asp-area="@submenu["area"]" class="menu-link">
                                            <span class="menu-text">@submenu["text"]</span>
                                        </a>
                                    </div>
                                }
                            </div>
                        }
                    </div>

                }

            }
            <div class="p-3 px-4 mt-auto hide-on-minified">
                <a href="https://github.com/jcguimaraesnet/projeto-bloco-social-network/blob/master/README.md" class="btn d-block w-100 btn-secondary font-weight-600 rounded-pill" target="_blank">
                    <i class="fa fa-code-branch me-1 ms-n1 opacity-5"></i> ReadMe.md
                </a>
            </div>
        </div>
        <!-- END menu -->
    </div>
    <!-- END scrollbar -->
    <!-- BEGIN mobile-sidebar-backdrop -->
    <button class="app-sidebar-mobile-backdrop" data-dismiss="sidebar-mobile"></button>
    <!-- END mobile-sidebar-backdrop -->
</div>
<!-- END #sidebar -->